parabol_uploader:
    path: /_uploader/upload
    defaults:  { _controller: ParabolFilesUploadBundle:Blueimp:upload }
    options: { i18n: false }

parabol_uploader_get:
    path: /_uploader/get
    defaults:  { _controller: ParabolFilesUploadBundle:Blueimp:get }
    options: { i18n: false }

parabol_uploader_delete:
    path: /_uploader/delete/{id}
    defaults:  { _controller: ParabolFilesUploadBundle:Blueimp:delete }
    options: { i18n: false }

parabol_uploader_update_file:
    path: /_uploader/update/file/{id}
    defaults:  { _controller: ParabolFilesUploadBundle:Blueimp:updateFile }
    options: { i18n: false }

# parabol_uploader_update_pos:
#     path: /_uploader/update-position
#     defaults:  { _controller: ParabolFilesUploadBundle:Blueimp:updatePosition }
#     options: { i18n: false }

