services:
    parabol.subscriber.file_relation:
        class: Parabol\FilesUploadBundle\EventListener\FileRelationSubscriber
        arguments:
            - "@service_container"
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
        tags:
            - { name: doctrine.event_subscriber, connection: default }        

    parabol.type_extension.blueimp_upload:
        class: Parabol\FilesUploadBundle\Form\Type\BlueimpType
        tags:
            - { name: form.type, alias: blueimp_upload }

    parabol.helper.blueimp_file:
        class: Parabol\FilesUploadBundle\Service\BlueimpFileHelper
        arguments:
            - "@router"
            - "@liip_imagine.cache.manager"
