parameters:
    parabol.file_info_form.class: Parabol\FilesUploadBundle\Form\Type\FileInfoFormType


services:
    parabol.subscriber.file_relation:
        class: Parabol\FilesUploadBundle\EventListener\FileRelationSubscriber
        arguments:
            - "@service_container"
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
        tags:
            - { name: doctrine.event_subscriber, connection: default }        

    Parabol\FilesUploadBundle\Form\Type\BlueimpType:
        arguments: [ "%parabol.file_info_form.class%" ]
        tags:
            - { name: form.type}

    blueimp_upload:
        alias: Parabol\FilesUploadBundle\Form\Type\BlueimpType


    parabol.helper.blueimp_file:
        class: Parabol\FilesUploadBundle\Service\BlueimpFileHelper
        public: true
        arguments:
            - "@router"
            - "@liip_imagine.cache.manager"

    Parabol\FilesUploadBundle\Form\Base\Extension\AdminBaseTypeExtension:
        arguments: 
            - "@=service('kernel').getBundles()"
            - "@=service('kernel').getEnvironment()"
        tags:
            -  { name: parabol.admin_base_type_extension }

    app.bluimp.extension:
        class: Parabol\FilesUploadBundle\Form\Base\Extension\SonataAdminBluimpTypeExtension  
        tags:
            - { name: sonata.admin.extension, global: true }
