parameters:
    parabol.files_uploads.file_info_form.class: Parabol\FilesUploadBundle\Form\Type\FileInfoFormType
    parabol.files_uploads.filemanager_modal_selector: null
    parabol.files_uploads.filemanager_path: '/admin/manager?module=1&conf=button'

services:
    parabol.subscriber.file_relation:
        class: Parabol\FilesUploadBundle\EventListener\FileRelationSubscriber
        arguments:
            - "@service_container"
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
        tags:
            - { name: doctrine.event_subscriber, connection: default }        

    parabol.type_extension.blueimp_upload:
        class: Parabol\FilesUploadBundle\Form\Type\BlueimpType
        arguments: 
            $configuration: 
                fileInfoFormClass: '%parabol.files_uploads.file_info_form.class%'
                filemanagerModalSelector: '%parabol.files_uploads.filemanager_modal_selector%'
                filemanagerPath: '%parabol.files_uploads.filemanager_path%'
        tags:
            - { name: form.type, alias: blueimp_upload }

    parabol.helper.blueimp_file:
        class: Parabol\FilesUploadBundle\Service\BlueimpFileHelper
        public: true
        arguments:
            - "@router"
            - "@liip_imagine.cache.manager"

    Parabol\FilesUploadBundle\Form\Base\Extension\AdminBaseTypeExtension:
        arguments: 
            - "@=service('kernel').getBundles()"
            - "@=service('kernel').getEnvironment()"
        tags:
            -  { name: parabol.admin_base_type_extension }

    app.bluimp.extension:
        class: Parabol\FilesUploadBundle\Form\Base\Extension\SonataAdminBluimpTypeExtension  
        tags:
            - { name: sonata.admin.extension, global: true }
