<?php

namespace Parabol\FilesUploadBundle\Entity;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends \Parabol\BaseBundle\Entity\Base\BaseRepository
{
	
	use \Parabol\DoctrineBehaviorsBundle\Sortable\Entity\SortableRepository;

	protected function addSortingScope(\Doctrine\ORM\QueryBuilder $qb, $entity)
    {
    	$qb
    		->andWhere('e.class = :class')
    		->andWhere('e.ref = :ref')
            ->andWhere('e.context = :context')
    		->setParameter('class', $entity->getClass())
    		->setParameter('ref', $entity->getRef())
            ->setParameter('context', $entity->getContext())
    		;
    }
}
